import {
	Audience,
	Categories,
	Game,
	// Dashboard,
	Login,
	Logout,
	Player,
	Questions,
	QuizDetails,
	QuizQuestions,
	Quizzes,
	Register,
	Welcome,
} from "pages";
import {
	LogoutOutlined,
	SolutionOutlined,
	AppstoreOutlined,
	ProfileOutlined,
	// DashboardOutlined,
} from "@ant-design/icons";

const routes = [
	{
		name: "Home",
		component: Welcome,
		auth: false,
		path: "/",
		exact: true,
		show: true,
	},
	// {
	// 	name: "Dashboard",
	// 	component: Dashboard,
	// 	auth: true,
	// 	path: "/dashboard",
	// 	exact: true,
	// show: false
	// 	icon: <DashboardOutlined />,
	// },
	{
		name: "Login",
		component: Login,
		auth: false,
		path: "/login",
		exact: true,
		show: true,
	},
	{
		name: "Register",
		component: Register,
		auth: false,
		path: "/register",
		exact: true,
		show: true,
	},
	{
		name: "Categories",
		component: Categories,
		auth: true,
		path: "/categories",
		exact: true,
		show: true,
		icon: <AppstoreOutlined />,
	},
	{
		name: "Questions",
		component: Questions,
		auth: true,
		path: "/questions",
		exact: true,
		show: true,
		icon: <ProfileOutlined />,
	},
	{
		name: "Quizzes",
		component: Quizzes,
		auth: true,
		path: "/quizzes",
		exact: true,
		show: true,
		icon: <SolutionOutlined />,
	},
	{
		name: "Quiz Details",
		component: QuizDetails,
		auth: true,
		path: "/quizzes/:id",
		exact: true,
		show: false,
		icon: null,
	},
	{
		name: "Quiz Questions",
		component: QuizQuestions,
		auth: true,
		path: "/quizzes/:id/questions",
		exact: true,
		show: false,
		icon: null,
	},
	{
		name: "Game",
		component: Game,
		auth: true,
		path: "/quizzes/:id/game",
		exact: true,
		show: false,
		icon: null,
	},
	{
		name: "Player",
		component: Player,
		auth: false,
		path: "/quizzes/:quizId/players/:playerId",
		exact: true,
		show: false,
		icon: null,
	},
	{
		name: "audience",
		component: Audience,
		auth: true,
		path: "/quizzes/:quizId/audience",
		exact: true,
		show: false,
		icon: null,
	},
	{
		name: "Logout",
		component: Logout,
		auth: true,
		path: "/logout",
		exact: true,
		show: true,
		icon: <LogoutOutlined />,
	},
];

export default routes;
